ALTER TABLE events ADD COLUMN duration_hours INT NULL;
ALTER TABLE events ADD COLUMN age_limit VARCHAR(50) NULL;
ALTER TABLE events ADD COLUMN languages VARCHAR(255) NULL;
ALTER TABLE events ADD COLUMN genres VARCHAR(255) NULL;
ALTER TABLE events ADD COLUMN event_highlights TEXT NULL;
