SET NAMES utf8mb4;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS can_post_events TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS can_create_influencer_profile TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS can_post_deals TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE influencers
  ADD COLUMN IF NOT EXISTS contact_email VARCHAR(190) NULL AFTER social_links;

ALTER TABLE deals
  ADD COLUMN IF NOT EXISTS promo_code VARCHAR(80) NULL AFTER deal_link;

